/* eslint-disable @typescript-eslint/no-unused-vars */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import sqlite3 from "sqlite3";
import { open } from "sqlite";

const inter = Inter({ subsets: ["latin"] });

async function openDB() {
  return open({
    filename: "./mydb.sqlite",
    driver: sqlite3.Database,
  });
}

type People = {
  name: string;
  email: string;
  age: number;
  gender: string;
};

export const getStaticProps: GetStaticProps<{ people: People[] }> = async (
  context
) => {
  const db = await openDB();
  const people = await db.all("select * from person");
  return {
    props: {
      people,
    },
  };
};

export default function Home({
  people,
}: {
  people: {
    name: string;
    email: string;
    age: number;
    gender: string;
  }[];
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1 className="text-3xl font-bold underline text-yellow-100 italic">Hello, Next.js!</h1>
          {people.map(({ name, email, age, gender }) => (
            <>
              <div>{name}</div>
              <div>{email}</div>
              <div>{age}</div>
              <div>{gender}</div>
            </>
          ))}  
        </div>
      </main>
    </>
  );
}
