/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable no-magic-numbers */
/* eslint-disable indent */
/* eslint-disable @typescript-eslint/no-unused-vars */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { GetStaticProps, GetStaticPaths } from "next";
import { useRouter } from 'next/router';
import openDB from "@/utils/db";
import { getAllPersonId } from "@/lib/vehicles";

const inter = Inter({ subsets: ["latin"] });

type Vehicle = {
  brand: string;
  model: string;
  ownerId: number;
};
export const getStaticPaths: GetStaticPaths = async () => {
  const paths = await getAllPersonId();
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) =>  {
  const db = await openDB();
  const vehicles = await db.all('select * from vehicle where ownerId = ?', params?.id);
    return {
      props: {
        vehicles,
      },
  };
};

export default function VehicleByPersonId({ vehicles }: { vehicles: Vehicle[] }) {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className="px-4 sm:px-0">
            <h3 className="text-base font-semibold leading-7 text-white-900">
              Information
            </h3>
            <p className="mt-1 max-w-2xl text-sm leading-6 text-white-500">
              Personal details and application.
            </p>
          </div>
          <div className="mt-6 border-t border-white-100">
            <dl className="divide-y divide-white-100">
              <div className="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                <dt className="text-sm font-medium leading-6 text-white-900">
                  Brand
                </dt>
                <dd className="mt-1 text-sm leading-6 text-white-700 sm:col-span-2 sm:mt-0">
                  {
                    vehicles.map(item => (
                      <>
                        <div>{item.brand}</div>
                      </>
                    ))
                  }
                </dd>
              </div>
              <div className="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                <dt className="text-sm font-medium leading-6 text-white-900">
                  Model
                </dt>
                <dd className="mt-1 text-sm leading-6 text-white-700 sm:col-span-2 sm:mt-0">
                {
                    vehicles.map(item => (
                      <>
                        <div>
                          {item.model}
                        </div>
                      </>
                    ))
                  }
                </dd>
              </div>
            </dl>
          </div>
        </div>
      </main>
    </>
  );
}
