// import './globals.css'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

import styles from './layout.module.css'
import Link from 'next/link';

export const metadata = {
    title: 'Wunna',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>Next.js</title>
            </head>
            <body>
                <div className={styles.header}>
                    <div>
                        <h1 style={{ marginTop: 0 }}>From layout</h1>
                    </div>
                    <div>
                        <Link href="/profile/teacher">navigate to teacher profile</Link>
                    </div>
                    <div>
                        <Link href="/profile/student">navigate to student profile</Link>
                    </div>
                </div>
                <div>{children}</div>
            </body>
        </html>
    )
}
